# Example 5

In this example, we evolve a list of  binary systems (in the file [listBin.dat](listBin.dat)) then we run SEVN  in parallel using more than one thread. Finally, we show how to gather the information stored in the outputs of the different threds

- To compile SEVN use the [compile.sh](compile.sh) script
- The run in parappel use [run_multi.sh](run_multi.sh)


Remember to set the proper SEVN path in the compile and run scripts

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
#Cycle over the output files and concat them 
import glob
outfiles=glob.glob("sevn_output/output_*")

dfs=[]
for outfile in outfiles:
    dfs.append(pd.read_csv(outfile))
    
df=pd.concat(dfs)
display(df)

,ID,name,Mass_0,MHE_0,MCO_0,Radius_0,Luminosity_0,Temperature_0,Phase_0,RemnantType_0,...,MCO_1,Radius_1,Luminosity_1,Temperature_1,Phase_1,RemnantType_1,BWorldtime,Semimajor,Eccentricity,BEvent
0,134,249011559042371,13.924620,0.0,0.0,4.893605,16537.930000,29589.15,1,0,...,0.000000,4.562710,11333.760000,27881.020,1,0,0.000000,63.10000,0.276000,-1
1,134,249011559042371,13.917190,0.0,0.0,5.172441,17533.540000,29204.26,1,0,...,0.000000,4.776972,11838.120000,27546.790,1,0,1.182543,63.12059,0.275989,-1
2,134,249011559042371,13.910310,0.0,0.0,5.445246,18510.480000,28851.76,1,0,...,0.000000,4.984684,12325.970000,27240.370,1,0,2.279356,63.13918,0.275977,-1
3,134,249011559042371,13.903430,0.0,0.0,5.733140,19554.160000,28506.25,1,0,...,0.000000,5.212203,12924.010000,26956.610,1,0,3.373988,63.15768,0.275960,-1
4,134,249011559042371,13.894150,0.0,0.0,6.111103,21038.840000,28120.45,1,0,...,0.000000,5.469897,13708.890000,26704.690,1,0,4.463918,63.18090,0.275937,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29731,133,258011183685381,1.531436,0.0,0.0,0.000016,0.001552,288097.20,7,5,...,2.756160,526.319200,92162.420000,4383.696,6,0,15.282710,NaN,NaN,-1
29732,133,258011183685381,1.531436,0.0,0.0,0.000016,0.001550,287999.60,7,5,...,2.756160,544.668500,97170.740000,4366.609,6,0,15.285520,NaN,NaN,-1
29733,133,258011183685381,1.531436,0.0,0.0,0.000016,0.001547,287884.00,7,5,...,2.759190,560.201900,101415.600000,4351.915,6,0,15.288840,NaN,NaN,-1
29734,133,258011183685381,1.531436,0.0,0.0,0.000016,0.001545,287789.70,7,5,...,2.764965,572.526800,104805.700000,4340.352,6,0,15.291560,NaN,NaN,-1
29735,133,258011183685381,1.531436,0.0,0.0,0.000016,0.001545,287789.70,7,5,...,0.000000,0.000016,2.330785,1793564.000,7,5,15.291560,NaN,NaN,0

In [7]:
#One can exploit the file splitting to operate in parallel (e.g. filtering)
#Define a function to call in parallel
def filterBCO_df(ifile):
    df=pd.read_csv(ifile)
    df=df[df.Semimajor.notnull() & (df.Phase_0==7) & (df.Phase_1==7)]
    return df

from multiprocess import Pool 

#Use the multiprocess library (pip instal multiprocess) to spawn 3 processes each one working on a separate file
outfiles=glob.glob("sevn_output/output_*")
with Pool(3) as pool:
    dfl=pool.map(filterBCO_df,outfiles)

#Finally generate the final file
df=pd.concat(dfl)
display(df)

,ID,name,Mass_0,MHE_0,MCO_0,Radius_0,Luminosity_0,Temperature_0,Phase_0,RemnantType_0,...,MCO_1,Radius_1,Luminosity_1,Temperature_1,Phase_1,RemnantType_1,BWorldtime,Semimajor,Eccentricity,BEvent
481,134,249011559042371,1.196248,0.0,0.0,0.000016,0.022743,563708.20,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,14.332250,3.862177,0.587382,0
4193,143,713632802128999,1.308870,0.0,0.0,0.000016,0.002573,326936.00,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,23.472700,0.631064,0.205871,0
4621,144,460052195926563,1.195264,0.0,0.0,0.000016,0.029228,600194.80,7,5,...,0.0,0.000016,2.298446,1787310.0,7,5,17.000420,0.783667,0.567848,0
5940,147,233903024933446,1.196707,0.0,0.0,0.000016,0.001530,287071.80,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,18.835500,0.528343,0.464134,0
7944,152,885258845145985,1.274381,0.0,0.0,0.000016,0.002034,308271.50,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,26.019120,0.202604,0.105236,0
9512,155,380536783091563,1.379855,0.0,0.0,0.002743,6.041581,172782.30,7,3,...,0.0,0.000016,2.249976,1777811.0,7,5,16.815940,2.092559,0.217437,0
10022,156,179118781457684,1.195904,0.0,0.0,0.000016,0.000912,252247.80,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,21.015620,0.554050,0.302089,0
10467,157,778983488154387,1.193323,0.0,0.0,0.000016,0.071975,751858.70,7,5,...,0.0,0.000016,2.400775,1806879.0,7,5,20.915030,0.800863,0.643402,0
16087,170,586150857774112,1.305064,0.0,0.0,0.000016,0.021481,555719.80,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,20.889050,1.334913,0.429495,0
18086,175,805084070482156,1.193327,0.0,0.0,0.000016,0.001096,264097.40,7,5,...,0.0,0.000016,2.294493,1786541.0,7,5,23.012820,0.498850,0.440200,0
22724,185,414877179726658,1.206634,0.0,0.0,0.000016,0.048339,680635.40,7,5,...,0.0,0.000016,2.525741,1829947.0,7,5,9.953684,0.835942,0.643372,0
3312,7,718081486160246,1.194290,0.0,0.0,0.000016,0.004959,385197.10,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,15.913950,2.486745,0.034068,0
4653,10,319537558443775,1.370273,0.0,0.0,0.002959,0.444059,86624.58,7,3,...,0.0,0.000016,2.249976,1777811.0,7,5,19.529370,0.398883,0.339659,0
6644,14,815773448527661,1.264664,0.0,0.0,0.000016,0.004816,382402.00,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,20.860440,1.475578,0.251623,0
7907,17,763169102478390,1.194107,0.0,0.0,0.000016,0.000901,251523.80,7,5,...,0.0,0.005843,41.840390,192042.8,7,2,32.816070,0.422573,0.000000,11
8374,18,297411657537333,1.194990,0.0,0.0,0.000016,0.001298,275515.90,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,23.222660,0.614912,0.291284,0
9740,21,163022202186861,1.194155,0.0,0.0,0.000016,0.003134,343451.50,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,17.585850,1.935133,0.099722,0
10237,22,324460045223055,1.218364,0.0,0.0,0.000016,0.004721,380502.20,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,13.842500,8.966006,0.564055,0
11569,25,582840730235000,1.197203,0.0,0.0,0.000016,0.001536,287376.60,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,20.593830,0.337254,0.316900,0
12019,26,525348128872105,1.311717,0.0,0.0,0.000016,0.117664,850162.10,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,20.258450,1.307990,0.481488,0
12783,28,359624091160444,1.358738,0.0,0.0,0.003201,1.862801,119189.50,7,2,...,0.0,0.000016,2.249976,1777811.0,7,5,22.316510,0.836033,0.635702,0
13231,29,580974700986687,1.195119,0.0,0.0,0.000016,0.024302,573129.20,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,18.953470,0.941403,0.553241,0
13651,30,302654596356341,1.195542,0.0,0.0,0.000016,0.017983,531563.90,7,5,...,0.0,0.003392,260.112300,397982.0,7,2,17.558690,0.837174,0.000000,11
14571,32,466145683075356,1.194516,0.0,0.0,0.000016,0.001299,275556.00,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,22.112240,1.120953,0.464819,0
17332,38,828731913221562,1.330426,0.0,0.0,0.003737,2.466604,118335.00,7,3,...,0.0,0.000016,2.249976,1777811.0,7,5,20.953710,2.562671,0.392272,0
20205,44,913669216791958,1.193336,0.0,0.0,0.000016,1.306925,1552043.00,7,5,...,0.0,0.000016,2.320677,1791616.0,7,5,15.359850,27.268720,0.689538,0
21180,46,860162065703663,1.196754,0.0,0.0,0.000016,0.010361,463117.90,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,20.061370,0.440764,0.327295,0
27174,60,844026595967205,1.197470,0.0,0.0,0.000016,0.000712,237143.40,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,19.937740,0.344428,0.375512,0
28564,63,329231420085812,1.641315,0.0,0.0,0.000016,0.064845,732504.00,7,5,...,0.0,0.000016,2.574197,1838661.0,7,5,10.984950,19.255240,0.956248,0
29474,65,132220226652677,1.195623,0.0,0.0,0.000016,0.000470,213731.50,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,23.515610,1.367625,0.103515,0
397,67,566164905063477,1.195234,0.0,0.0,0.000016,0.035449,629858.50,7,5,...,0.0,0.000016,2.360449,1799243.0,7,4,17.324580,0.749482,0.056918,0
1773,70,830609267086271,1.193511,0.0,0.0,0.000016,2.250338,1777883.00,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,18.598360,0.758318,0.568262,0
2169,71,549566087943853,1.194682,0.0,0.0,0.000016,0.097529,811194.50,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,16.762340,0.939298,0.092587,0
2619,72,677798603860436,1.194628,0.0,0.0,0.000016,0.027507,591155.60,7,5,...,0.0,0.000016,2.380674,1803085.0,7,4,14.699600,1.645354,0.034019,0
4690,77,680226711002334,1.193223,0.0,0.0,0.000016,2.249976,1777811.00,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,17.231480,0.960397,0.569133,0
5143,78,482654376193838,1.309200,0.0,0.0,0.000016,0.000521,219258.10,7,4,...,0.0,0.000016,2.376191,1802236.0,7,4,27.890660,0.449021,0.042258,0
5564,79,329804723339200,1.194298,0.0,0.0,0.000016,0.090543,796260.50,7,5,...,0.0,0.000016,2.383179,1803559.0,7,4,17.832310,0.964525,0.068269,0
5988,80,737483593765312,1.193753,0.0,0.0,0.000016,0.006148,406472.20,7,5,...,0.0,0.000016,2.392298,1805282.0,7,4,18.024710,3.849355,0.086168,0
6820,82,579731819314322,1.307594,0.0,0.0,0.000016,0.041421,654858.50,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,21.240000,1.043594,0.268419,0
9819,88,234777503290261,1.202279,0.0,0.0,0.000016,0.001623,291347.10,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,20.520730,0.531921,0.196059,0
10764,90,658660917368748,1.194170,0.0,0.0,0.000016,0.087053,788472.60,7,5,...,0.0,0.000016,2.392970,1805409.0,7,4,18.297890,0.936484,0.040504,0
12183,93,807789795975926,1.194136,0.0,0.0,0.000016,0.005423,393921.30,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,18.156810,1.841472,0.094726,0
14458,98,290464828425754,1.288626,0.0,0.0,0.000016,0.000870,249314.60,7,4,...,0.0,0.003956,46.444030,239561.4,7,2,27.995870,0.207147,0.000000,11
16074,102,205590147036331,1.196280,0.0,0.0,0.000016,0.014000,499311.40,7,5,...,0.0,0.000016,2.394711,1805737.0,7,4,16.216850,0.898509,0.059076,0
16499,103,735290831611938,1.194104,0.0,0.0,0.000016,0.001072,262646.10,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,27.458900,0.473438,0.095458,0
18626,108,934100196665420,1.264591,0.0,0.0,0.000016,0.001224,271506.20,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,21.979110,2.266906,0.171593,0
21245,114,956263530352473,1.267854,0.0,0.0,0.000016,0.003404,350633.80,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,25.562790,0.392750,0.169434,0
21685,115,278872164994031,1.194951,0.0,0.0,0.000016,0.008740,443836.00,7,5,...,0.0,0.000016,2.375640,1802131.0,7,4,16.129080,1.651329,0.057679,0
22069,116,301778420902244,1.233267,0.0,0.0,0.000016,0.000078,136517.40,7,5,...,0.0,0.016357,37.985780,112042.2,7,1,34.036180,0.625066,0.000000,0
23270,119,129298652784471,1.194645,0.0,0.0,0.000016,0.000385,203385.10,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,23.530040,0.528885,0.227166,0
28813,131,965811070944054,1.193867,0.0,0.0,0.000016,0.001346,278039.40,7,5,...,0.0,0.000016,2.393848,1805574.0,7,4,18.636010,2.619859,0.059092,0

In [9]:
#Alternative using dask  dataframe (pip install dask, see https://docs.dask.org/en/stable/dataframe.html)
import dask.dataframe as dd

dfd=dd.read_csv("sevn_output/output_*")
display(dfd)
df=dfd.compute()
display(df)

Dask DataFrame Structure:
                  ID   name   Mass_0    MHE_0    MCO_0 Radius_0 Luminosity_0 Temperature_0 Phase_0 RemnantType_0   Mass_1    MHE_1    MCO_1 Radius_1 Luminosity_1 Temperature_1 Phase_1 RemnantType_1 BWorldtime Semimajor Eccentricity BEvent
npartitions=3
               int64  int64  float64  float64  float64  float64      float64       float64   int64         int64  float64  float64  float64  float64      float64       float64   int64         int64    float64   float64      float64  int64
                 ...    ...      ...      ...      ...      ...          ...           ...     ...           ...      ...      ...      ...      ...          ...           ...     ...           ...        ...       ...          ...    ...
                 ...    ...      ...      ...      ...      ...          ...           ...     ...           ...      ...      ...      ...      ...          ...           ...     ...           ...        ...       ...          ...    ...
                 ...    ...      ...      ...      ...      ...          ...           ...     ...           ...      ...      ...      ...      ...          ...           ...     ...           ...        ...       ...          ...    ...
Dask Name: read-csv, 1 graph layer

,ID,name,Mass_0,MHE_0,MCO_0,Radius_0,Luminosity_0,Temperature_0,Phase_0,RemnantType_0,...,MCO_1,Radius_1,Luminosity_1,Temperature_1,Phase_1,RemnantType_1,BWorldtime,Semimajor,Eccentricity,BEvent
0,0,750428192974390,13.657820,0.0,0.0,3.431878,15591.010000,34816.03,1,0,...,0.0,2.827509,6306.507,30589.460,1,0,0.000000,36.50000,0.126000,-1
1,0,750428192974390,13.657160,0.0,0.0,3.595213,16655.690000,34582.39,1,0,...,0.0,2.938932,6586.923,30332.100,1,0,1.375409,36.50060,0.125993,-1
2,0,750428192974390,13.656490,0.0,0.0,3.760563,17797.420000,34378.70,1,0,...,0.0,3.025707,6886.093,30227.790,1,0,2.750817,36.50096,0.125982,-1
3,0,750428192974390,13.655790,0.0,0.0,3.941882,19078.050000,34167.11,1,0,...,0.0,3.114290,7213.288,30142.580,1,0,4.126226,36.50100,0.125967,-1
4,0,750428192974390,13.654980,0.0,0.0,4.155663,20601.520000,33921.99,1,0,...,0.0,3.205465,7556.030,30057.610,1,0,5.501634,36.50061,0.125944,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28774,199,118131375996867,1.193224,0.0,0.0,0.000016,0.009697,455518.40,7,5,...,0.0,81.607940,47506.940,9432.996,3,0,13.828580,407.83760,0.770853,-1
28775,199,118131375996867,1.193224,0.0,0.0,0.000016,0.009695,455492.50,7,5,...,0.0,86.095460,47295.520,9173.635,3,0,13.828750,404.04030,0.768703,-1
28776,199,118131375996867,1.193224,0.0,0.0,0.000016,0.009693,455467.70,7,5,...,0.0,91.383530,47022.610,8891.383,3,0,13.828920,398.18550,0.765326,-1
28777,199,118131375996867,1.193224,0.0,0.0,0.000016,0.009691,455446.30,7,5,...,0.0,96.213560,46788.070,8654.505,3,0,13.829060,389.92860,0.760427,-1
28778,199,118131375996867,1.193224,0.0,0.0,0.000016,0.009691,455446.30,7,5,...,NaN,NaN,NaN,NaN,7,-1,13.829060,NaN,NaN,13

In [11]:
#Filter 
dfd=dd.read_csv("sevn_output/output_*")
dfd=dfd[dfd.Semimajor.notnull() & (dfd.Phase_0==7) & (dfd.Phase_1==7)]
display(dfd)
df=dfd.compute()
display(df)

Dask DataFrame Structure:
                  ID   name   Mass_0    MHE_0    MCO_0 Radius_0 Luminosity_0 Temperature_0 Phase_0 RemnantType_0   Mass_1    MHE_1    MCO_1 Radius_1 Luminosity_1 Temperature_1 Phase_1 RemnantType_1 BWorldtime Semimajor Eccentricity BEvent
npartitions=3
               int64  int64  float64  float64  float64  float64      float64       float64   int64         int64  float64  float64  float64  float64      float64       float64   int64         int64    float64   float64      float64  int64
                 ...    ...      ...      ...      ...      ...          ...           ...     ...           ...      ...      ...      ...      ...          ...           ...     ...           ...        ...       ...          ...    ...
                 ...    ...      ...      ...      ...      ...          ...           ...     ...           ...      ...      ...      ...      ...          ...           ...     ...           ...        ...       ...          ...    ...
                 ...    ...      ...      ...      ...      ...          ...           ...     ...           ...      ...      ...      ...      ...          ...           ...     ...           ...        ...       ...          ...    ...
Dask Name: getitem, 10 graph layers

,ID,name,Mass_0,MHE_0,MCO_0,Radius_0,Luminosity_0,Temperature_0,Phase_0,RemnantType_0,...,MCO_1,Radius_1,Luminosity_1,Temperature_1,Phase_1,RemnantType_1,BWorldtime,Semimajor,Eccentricity,BEvent
3312,7,718081486160246,1.194290,0.0,0.0,0.000016,0.004959,385197.10,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,15.913950,2.486745,0.034068,0
4653,10,319537558443775,1.370273,0.0,0.0,0.002959,0.444059,86624.58,7,3,...,0.0,0.000016,2.249976,1777811.0,7,5,19.529370,0.398883,0.339659,0
6644,14,815773448527661,1.264664,0.0,0.0,0.000016,0.004816,382402.00,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,20.860440,1.475578,0.251623,0
7907,17,763169102478390,1.194107,0.0,0.0,0.000016,0.000901,251523.80,7,5,...,0.0,0.005843,41.840390,192042.8,7,2,32.816070,0.422573,0.000000,11
8374,18,297411657537333,1.194990,0.0,0.0,0.000016,0.001298,275515.90,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,23.222660,0.614912,0.291284,0
9740,21,163022202186861,1.194155,0.0,0.0,0.000016,0.003134,343451.50,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,17.585850,1.935133,0.099722,0
10237,22,324460045223055,1.218364,0.0,0.0,0.000016,0.004721,380502.20,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,13.842500,8.966006,0.564055,0
11569,25,582840730235000,1.197203,0.0,0.0,0.000016,0.001536,287376.60,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,20.593830,0.337254,0.316900,0
12019,26,525348128872105,1.311717,0.0,0.0,0.000016,0.117664,850162.10,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,20.258450,1.307990,0.481488,0
12783,28,359624091160444,1.358738,0.0,0.0,0.003201,1.862801,119189.50,7,2,...,0.0,0.000016,2.249976,1777811.0,7,5,22.316510,0.836033,0.635702,0
13231,29,580974700986687,1.195119,0.0,0.0,0.000016,0.024302,573129.20,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,18.953470,0.941403,0.553241,0
13651,30,302654596356341,1.195542,0.0,0.0,0.000016,0.017983,531563.90,7,5,...,0.0,0.003392,260.112300,397982.0,7,2,17.558690,0.837174,0.000000,11
14571,32,466145683075356,1.194516,0.0,0.0,0.000016,0.001299,275556.00,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,22.112240,1.120953,0.464819,0
17332,38,828731913221562,1.330426,0.0,0.0,0.003737,2.466604,118335.00,7,3,...,0.0,0.000016,2.249976,1777811.0,7,5,20.953710,2.562671,0.392272,0
20205,44,913669216791958,1.193336,0.0,0.0,0.000016,1.306925,1552043.00,7,5,...,0.0,0.000016,2.320677,1791616.0,7,5,15.359850,27.268720,0.689538,0
21180,46,860162065703663,1.196754,0.0,0.0,0.000016,0.010361,463117.90,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,20.061370,0.440764,0.327295,0
27174,60,844026595967205,1.197470,0.0,0.0,0.000016,0.000712,237143.40,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,19.937740,0.344428,0.375512,0
28564,63,329231420085812,1.641315,0.0,0.0,0.000016,0.064845,732504.00,7,5,...,0.0,0.000016,2.574197,1838661.0,7,5,10.984950,19.255240,0.956248,0
29474,65,132220226652677,1.195623,0.0,0.0,0.000016,0.000470,213731.50,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,23.515610,1.367625,0.103515,0
397,67,566164905063477,1.195234,0.0,0.0,0.000016,0.035449,629858.50,7,5,...,0.0,0.000016,2.360449,1799243.0,7,4,17.324580,0.749482,0.056918,0
1773,70,830609267086271,1.193511,0.0,0.0,0.000016,2.250338,1777883.00,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,18.598360,0.758318,0.568262,0
2169,71,549566087943853,1.194682,0.0,0.0,0.000016,0.097529,811194.50,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,16.762340,0.939298,0.092587,0
2619,72,677798603860436,1.194628,0.0,0.0,0.000016,0.027507,591155.60,7,5,...,0.0,0.000016,2.380674,1803085.0,7,4,14.699600,1.645354,0.034019,0
4690,77,680226711002334,1.193223,0.0,0.0,0.000016,2.249976,1777811.00,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,17.231480,0.960397,0.569133,0
5143,78,482654376193838,1.309200,0.0,0.0,0.000016,0.000521,219258.10,7,4,...,0.0,0.000016,2.376191,1802236.0,7,4,27.890660,0.449021,0.042258,0
5564,79,329804723339200,1.194298,0.0,0.0,0.000016,0.090543,796260.50,7,5,...,0.0,0.000016,2.383179,1803559.0,7,4,17.832310,0.964525,0.068269,0
5988,80,737483593765312,1.193753,0.0,0.0,0.000016,0.006148,406472.20,7,5,...,0.0,0.000016,2.392298,1805282.0,7,4,18.024710,3.849355,0.086168,0
6820,82,579731819314322,1.307594,0.0,0.0,0.000016,0.041421,654858.50,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,21.240000,1.043594,0.268419,0
9819,88,234777503290261,1.202279,0.0,0.0,0.000016,0.001623,291347.10,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,20.520730,0.531921,0.196059,0
10764,90,658660917368748,1.194170,0.0,0.0,0.000016,0.087053,788472.60,7,5,...,0.0,0.000016,2.392970,1805409.0,7,4,18.297890,0.936484,0.040504,0
12183,93,807789795975926,1.194136,0.0,0.0,0.000016,0.005423,393921.30,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,18.156810,1.841472,0.094726,0
14458,98,290464828425754,1.288626,0.0,0.0,0.000016,0.000870,249314.60,7,4,...,0.0,0.003956,46.444030,239561.4,7,2,27.995870,0.207147,0.000000,11
16074,102,205590147036331,1.196280,0.0,0.0,0.000016,0.014000,499311.40,7,5,...,0.0,0.000016,2.394711,1805737.0,7,4,16.216850,0.898509,0.059076,0
16499,103,735290831611938,1.194104,0.0,0.0,0.000016,0.001072,262646.10,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,27.458900,0.473438,0.095458,0
18626,108,934100196665420,1.264591,0.0,0.0,0.000016,0.001224,271506.20,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,21.979110,2.266906,0.171593,0
21245,114,956263530352473,1.267854,0.0,0.0,0.000016,0.003404,350633.80,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,25.562790,0.392750,0.169434,0
21685,115,278872164994031,1.194951,0.0,0.0,0.000016,0.008740,443836.00,7,5,...,0.0,0.000016,2.375640,1802131.0,7,4,16.129080,1.651329,0.057679,0
22069,116,301778420902244,1.233267,0.0,0.0,0.000016,0.000078,136517.40,7,5,...,0.0,0.016357,37.985780,112042.2,7,1,34.036180,0.625066,0.000000,0
23270,119,129298652784471,1.194645,0.0,0.0,0.000016,0.000385,203385.10,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,23.530040,0.528885,0.227166,0
28813,131,965811070944054,1.193867,0.0,0.0,0.000016,0.001346,278039.40,7,5,...,0.0,0.000016,2.393848,1805574.0,7,4,18.636010,2.619859,0.059092,0
481,134,249011559042371,1.196248,0.0,0.0,0.000016,0.022743,563708.20,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,14.332250,3.862177,0.587382,0
4193,143,713632802128999,1.308870,0.0,0.0,0.000016,0.002573,326936.00,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,23.472700,0.631064,0.205871,0
4621,144,460052195926563,1.195264,0.0,0.0,0.000016,0.029228,600194.80,7,5,...,0.0,0.000016,2.298446,1787310.0,7,5,17.000420,0.783667,0.567848,0
5940,147,233903024933446,1.196707,0.0,0.0,0.000016,0.001530,287071.80,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,18.835500,0.528343,0.464134,0
7944,152,885258845145985,1.274381,0.0,0.0,0.000016,0.002034,308271.50,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,26.019120,0.202604,0.105236,0
9512,155,380536783091563,1.379855,0.0,0.0,0.002743,6.041581,172782.30,7,3,...,0.0,0.000016,2.249976,1777811.0,7,5,16.815940,2.092559,0.217437,0
10022,156,179118781457684,1.195904,0.0,0.0,0.000016,0.000912,252247.80,7,5,...,0.0,0.000016,2.249976,1777811.0,7,5,21.015620,0.554050,0.302089,0
10467,157,778983488154387,1.193323,0.0,0.0,0.000016,0.071975,751858.70,7,5,...,0.0,0.000016,2.400775,1806879.0,7,5,20.915030,0.800863,0.643402,0
16087,170,586150857774112,1.305064,0.0,0.0,0.000016,0.021481,555719.80,7,4,...,0.0,0.000016,2.249976,1777811.0,7,5,20.889050,1.334913,0.429495,0
18086,175,805084070482156,1.193327,0.0,0.0,0.000016,0.001096,264097.40,7,5,...,0.0,0.000016,2.294493,1786541.0,7,5,23.012820,0.498850,0.440200,0
22724,185,414877179726658,1.206634,0.0,0.0,0.000016,0.048339,680635.40,7,5,...,0.0,0.000016,2.525741,1829947.0,7,5,9.953684,0.835942,0.643372,0